name: Android APK Build

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.44.5

      - name: Get Packages
        run: flutter pub get

      - name: Patch Isar Android plugin
        run: |
          FILE="$HOME/.pub-cache/hosted/pub.dev/isar_flutter_libs-3.1.0+1/android/build.gradle"

            sed -i '/android {/a\    namespace "dev.isar.isar_flutter_libs"' "$FILE"

            sed -i 's/compileSdkVersion 30/compileSdkVersion 36/' "$FILE"

            cat "$FILE"

      - name: Generate Isar Files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk